# Generated by Django 4.2.5 on 2023-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=250)),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc2', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='name1',
        ),
    ]
